### ISSUE TITLE
åtkomst till existerande kalendrar

### ISSUE THREAD

**Issue by LukasWINGREN** [Itangalo/kursplaneringGo#1]
En intressant utveckling vore att man kunde komma åt existerande kalendrar. Många skolor har autogenererade googelkalendrar eller kalendrar kopplade till en lärplattform (exv google classsroom)

**Comment by Itangalo** [comment]
Ingen dum idé. Förslag på funktion:

* Ett nytt val i menyn "läs in kalender från id".
* Användaren måste först fylla i kalender-id i rutan för detta.
* Skriptet läser in samtliga händelser i kalendern (om detta är möjligt, har inte testat, annars säg ett år framåt), och fyller i starttid, sluttid, rubrik och _en_ kolumn med beskrivning. Rader fylls på längst ner i kalkylbladet, efter eventuella rader som användaren lagt in själv för hand.
* Rutan som innehåller namn på kalender uppdateras så att den avspeglar Google-kalenderns namn.

Frågor som kvarstår:

* Vad ska hända om användaren försöker uppdatera Google-kalendern? I det fall du beskriver lär det inte vara användaren som äger kalendern. Ska skriptet försöka kolla det, och ge felmeddelande om det inte funkar?
* Om det nästan aldrig är användaren själv som äger kalendern, är det bättre att ha det som två olika skript? Vill man pusha planering till Google-kalender använder man ena skriptet, vill man läsa Google-kalender till kalkylblad använder man andra.

**Comment by Itangalo** [comment]
Jag fick just idéer för mer komplexa (och mer användbara) sätt att lösa det här på:

* Ett nytt menyval "läs in Google-kalender".
* Om inget kalender-id finns angivet får man ett felmeddelande som säger att kalender-id behövs.
* Google-kalender läses in. Varje händelse _som inte redan finns i listan_ läggs till som en ny händelse. Varje händelse som matchar ett befintligt id blir istället uppdaterat.
* När händelser från Google-kalendern läses in försöker skriptet hitta rubriker som motsvarar de i kolumnerna för beskrivning, och dela av beskrinvingen enligt dem. Står det "Sidor i boken" i en beskrivning i Google-kalendern, och det är en rubrik i kalkylbladet, ska efterföljande text alltså hamna i den kolumnen. Annars hamnar allt i första kolumnen för beskrivning.
* Menyvalet "skapa/uppdatera valda kalenderhändelser" får en extra kontroll, för att se om användaren är behörig att redigera kalendern. Saknas behörighet visas ett felmeddelande.

Det här borde kunna användas för två olika use cases:

* En lärare vill läsa in en kalender som skolan delat, för att använda i en planering
* En lärare har pushat sin planering till Google-kalender och sedan gjort ändringar där, och vill läsa tillbaka dem

Den här approachen blir knepigare att få till. Är det värt det?

**Comment by LukasWINGREN** [comment]
Ditt sista förslag låter som en mycket bra utveckling. 
Ofta skapas kalendrar automatiskt men läraren har möjlighet att redigera och dela kalendern. 

Även i allmänna fallet vore det smidigt att kunna läsa in existerande kalendrar eftersom man kan ha gamla kalendrar som man vill kunna uppdatera smidigt framåt

**Comment by LukasWINGREN** [comment]
Det funkar ju bra redan nu att kopiera in kalender id (manuellt) och sedan lägga till nya händelser via kalkylbladet. Men som sagt vore bra att kunna läsa in och uppdatera redan inlagda events

**Comment by Itangalo** [comment]
Fixat i 1.3 beta! Har inte någon dokumentation/guide ännu, men det finns ett menyval "Läs in kalenderhändelser" som läser in kalenderhändelser ett år framåt och bakåt och lägger in i kalkylbladet. (Uppdaterar befintliga händelser om de har ett matchande id.)

**Comment by Itangalo** [comment]
Fixade en bugg till 1.4 beta. Stänger ärendet!
