### ISSUE TITLE
Lägga till plats/klassrum  

### ISSUE THREAD

**Issue by astrofys** [Itangalo/kursplaneringGo#3]
Det vore bra om man även kunde lägga in en kolumn för salen/platsen där undervisningen skall hållas.  Alla har ju inte lyxen av att ha samma klassrum hela tiden ;-)

**Comment by Itangalo** [comment]
Smart!

**Comment by Itangalo** [comment]
Fixat i version 1.5 beta, som nu är på plats! Visade sig bara behöva några få extra rader kod.
